name: my-content-engine

services:
  jaws_db:
    image: bitnami/postgresql:latest
    container_name: jaws_db
    environment:
      - POSTGRESQL_USERNAME=myuser
      - POSTGRESQL_PASSWORD=mypassword
      - POSTGRESQL_DATABASE=jaws_db
    ports:
      - "5432:5432"
    volumes:
      - jaws_db_data:/var/lib/postgresql/data



  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["./wait-for-it.sh", "jaws_db:5432", "--", "/app/entrypoint.sh"]
    image: ghcr.io/joshyorko/content-engine:latest

    environment:
     - .env

    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - jaws_db



volumes:
  jaws_db_data:
